[2025-04-25 08:17:57,929] - INFO - debug_pipeline - ========== Launching Data Ingestion Pipeline ==========
[2025-04-25 08:17:57,938] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-25 08:17:57,947] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-25 08:17:57,951] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-25 08:17:57,954] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-25 08:17:57,954] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Started ==========
[2025-04-25 08:17:57,954] - INFO - data_ingestion - ========== Starting Data Ingestion ==========
[2025-04-25 08:17:58,233] - INFO - mongodb_handler - MongoClient initialized.
[2025-04-25 08:18:01,090] - INFO - mongodb_handler - Exported 22110 documents from network_security_db.phishing_records as DataFrame.
[2025-04-25 08:18:01,162] - INFO - mongodb_handler - MongoClient connection closed.
[2025-04-25 08:18:01,162] - INFO - data_ingestion - Fetched 22110 raw rows from data source.
[2025-04-25 08:18:01,162] - INFO - core - Created directory for Raw Data: 'artifacts/2025_04_25T07_17_51Z/data_ingestion/featurestore'
[2025-04-25 08:18:01,262] - INFO - core - Raw Data saved to: 'artifacts/2025_04_25T07_17_51Z/data_ingestion/featurestore/raw_data.csv'
[2025-04-25 08:18:01,262] - INFO - core - Directory already exists for Raw Data: 'data/raw'
[2025-04-25 08:18:01,349] - INFO - core - Raw Data saved to: 'data/raw/raw_data.csv'
[2025-04-25 08:18:01,357] - INFO - data_ingestion - Raw DataFrame cleaned successfully.
[2025-04-25 08:18:01,357] - INFO - core - Created directory for Cleaned (Ingested) Data: 'artifacts/2025_04_25T07_17_51Z/data_ingestion/ingested'
[2025-04-25 08:18:01,428] - INFO - core - Cleaned (Ingested) Data saved to: 'artifacts/2025_04_25T07_17_51Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-25 08:18:01,428] - INFO - data_ingestion - ========== Data Ingestion Completed ==========
[2025-04-25 08:18:01,432] - INFO - data_ingestion_pipeline - Data Ingestion Process Completed.

Data Ingestion Artifact:
  - Raw Artifact:         'artifacts/2025_04_25T07_17_51Z/data_ingestion/featurestore/raw_data.csv'
  - Raw DVC Path:         'data/raw/raw_data.csv'
  - Ingested Data Path:   'artifacts/2025_04_25T07_17_51Z/data_ingestion/ingested/ingested_data.csv'

[2025-04-25 08:18:01,432] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Completed ==========
[2025-04-25 08:18:01,432] - INFO - debug_pipeline - ========== Data Ingestion Pipeline Finished ==========
[2025-04-25 08:18:01,432] - INFO - debug_pipeline - ======================================================
[2025-04-25 08:18:01,432] - INFO - debug_pipeline - ========== Launching Data Validation Pipeline ==========
[2025-04-25 08:18:01,440] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-25 08:18:01,446] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-25 08:18:01,449] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-25 08:18:01,453] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-25 08:18:01,453] - INFO - data_validation_pipeline - ========= Data Validation Stage Started =========
[2025-04-25 08:18:01,497] - INFO - core - Ingested Data loaded from: 'artifacts/2025_04_25T07_17_51Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-25 08:18:01,524] - INFO - core - Validated Base Data loaded from: 'data/validated/validated_data.csv'
[2025-04-25 08:18:01,524] - INFO - data_validation - Running data validation...
[2025-04-25 08:18:01,528] - INFO - data_validation - Schema hash check passed.
[2025-04-25 08:18:01,528] - INFO - core - Created directory for Missing Value Report: 'artifacts/2025_04_25T07_17_51Z/data_validation/reports'
[2025-04-25 08:18:01,528] - INFO - core - Missing Value Report saved to: 'artifacts/2025_04_25T07_17_51Z/data_validation/reports/missing_values_report.json'
[2025-04-25 08:18:01,541] - INFO - core - Directory already exists for Duplicates Report: 'artifacts/2025_04_25T07_17_51Z/data_validation/reports'
[2025-04-25 08:18:01,541] - INFO - core - Duplicates Report saved to: 'artifacts/2025_04_25T07_17_51Z/data_validation/reports/duplicates_report.yaml'
[2025-04-25 08:18:01,567] - INFO - core - Directory already exists for Drift Result: 'artifacts/2025_04_25T07_17_51Z/data_validation/reports'
[2025-04-25 08:18:01,571] - INFO - core - Drift Result saved to: 'artifacts/2025_04_25T07_17_51Z/data_validation/reports/drift_report.yaml'
[2025-04-25 08:18:01,571] - INFO - core - Directory already exists for Validation Report: 'artifacts/2025_04_25T07_17_51Z/data_validation/reports'
[2025-04-25 08:18:01,573] - INFO - core - Validation Report saved to: 'artifacts/2025_04_25T07_17_51Z/data_validation/reports/validation_report.yaml'
[2025-04-25 08:18:01,573] - INFO - core - Created directory for Validated Data: 'artifacts/2025_04_25T07_17_51Z/data_validation/validated'
[2025-04-25 08:18:01,595] - INFO - core - Validated Data saved to: 'artifacts/2025_04_25T07_17_51Z/data_validation/validated/validated_data.csv'
[2025-04-25 08:18:01,595] - INFO - core - Directory already exists for Validated Data: 'data/validated'
[2025-04-25 08:18:01,615] - INFO - core - Validated Data saved to: 'data/validated/validated_data.csv'
[2025-04-25 08:18:01,616] - INFO - data_validation_pipeline - Data Validation Process Completed.

Data Validation Artifact:
  - Validated Data Path: 'artifacts/2025_04_25T07_17_51Z/data_validation/validated/validated_data.csv'
  - Validation Status:   'True'

[2025-04-25 08:18:01,616] - INFO - data_validation_pipeline - ========= Data Validation Stage Completed =========
[2025-04-25 08:18:01,616] - INFO - debug_pipeline - ========== Data Validation Pipeline Finished ==========
[2025-04-25 08:18:01,616] - INFO - debug_pipeline - ======================================================
[2025-04-25 08:18:01,616] - INFO - debug_pipeline - ========== Launching Data Transformation Pipeline ==========
[2025-04-25 08:18:01,620] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-25 08:18:01,627] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-25 08:18:01,628] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-25 08:18:01,633] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-25 08:18:01,634] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Started ==========
[2025-04-25 08:18:01,657] - INFO - core - Validated Data loaded from: 'artifacts/2025_04_25T07_17_51Z/data_validation/validated/validated_data.csv'
[2025-04-25 08:18:01,657] - INFO - data_transformation - ========== Starting Data Transformation ==========
[2025-04-25 08:18:01,678] - INFO - core - Created directory for X Preprocessor Pipeline: 'artifacts/2025_04_25T07_17_51Z/data_transformation/preprocessor'
[2025-04-25 08:18:01,678] - INFO - core - X Preprocessor Pipeline saved to: 'artifacts/2025_04_25T07_17_51Z/data_transformation/preprocessor/x_preprocessor.joblib'
[2025-04-25 08:18:01,678] - INFO - core - Directory already exists for Y Preprocessor Pipeline: 'artifacts/2025_04_25T07_17_51Z/data_transformation/preprocessor'
[2025-04-25 08:18:01,678] - INFO - core - Y Preprocessor Pipeline saved to: 'artifacts/2025_04_25T07_17_51Z/data_transformation/preprocessor/y_preprocessor.joblib'
[2025-04-25 08:18:01,678] - INFO - core - Created directory for X_train: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/train'
[2025-04-25 08:18:01,681] - INFO - core - X_train saved to: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/train/x_train.npy'
[2025-04-25 08:18:01,681] - INFO - core - Directory already exists for X_train: 'data/transformed/train'
[2025-04-25 08:18:01,683] - INFO - core - X_train saved to: 'data/transformed/train/x_train.npy'
[2025-04-25 08:18:01,683] - INFO - core - Directory already exists for y_train: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/train'
[2025-04-25 08:18:01,683] - INFO - core - y_train saved to: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/train/y_train.npy'
[2025-04-25 08:18:01,683] - INFO - core - Directory already exists for y_train: 'data/transformed/train'
[2025-04-25 08:18:01,684] - INFO - core - y_train saved to: 'data/transformed/train/y_train.npy'
[2025-04-25 08:18:01,684] - INFO - core - Created directory for X_val: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/val'
[2025-04-25 08:18:01,685] - INFO - core - X_val saved to: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/val/x_val.npy'
[2025-04-25 08:18:01,685] - INFO - core - Directory already exists for X_val: 'data/transformed/val'
[2025-04-25 08:18:01,685] - INFO - core - X_val saved to: 'data/transformed/val/x_val.npy'
[2025-04-25 08:18:01,685] - INFO - core - Directory already exists for y_val: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/val'
[2025-04-25 08:18:01,686] - INFO - core - y_val saved to: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/val/y_val.npy'
[2025-04-25 08:18:01,686] - INFO - core - Directory already exists for y_val: 'data/transformed/val'
[2025-04-25 08:18:01,687] - INFO - core - y_val saved to: 'data/transformed/val/y_val.npy'
[2025-04-25 08:18:01,687] - INFO - core - Created directory for X_test: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/test'
[2025-04-25 08:18:01,687] - INFO - core - X_test saved to: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/test/x_test.npy'
[2025-04-25 08:18:01,687] - INFO - core - Directory already exists for X_test: 'data/transformed/test'
[2025-04-25 08:18:01,687] - INFO - core - X_test saved to: 'data/transformed/test/x_test.npy'
[2025-04-25 08:18:01,687] - INFO - core - Directory already exists for y_test: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/test'
[2025-04-25 08:18:01,689] - INFO - core - y_test saved to: 'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/test/y_test.npy'
[2025-04-25 08:18:01,689] - INFO - core - Directory already exists for y_test: 'data/transformed/test'
[2025-04-25 08:18:01,689] - INFO - core - y_test saved to: 'data/transformed/test/y_test.npy'
[2025-04-25 08:18:01,689] - INFO - data_transformation - ========== Data Transformation Completed ==========
[2025-04-25 08:18:01,690] - INFO - data_transformation_pipeline - Data Transformation Completed Successfully: 
Data Transformation Artifact:
  - X-Train Data Path:    'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/train/x_train.npy'
  - Y-Train Data Path:    'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/train/y_train.npy'
  - X-Val Data Path:      'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/val/x_val.npy'
  - Y-Val Data Path:      'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/val/y_val.npy'
  - X-Test Data Path:     'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/test/x_test.npy'
  - Y-Test Data Path:     'artifacts/2025_04_25T07_17_51Z/data_transformation/transformed/test/y_test.npy'

[2025-04-25 08:18:01,690] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Completed ==========
[2025-04-25 08:18:01,690] - INFO - debug_pipeline - ========== Data Transformation Pipeline Finished ==========
[2025-04-25 08:18:01,690] - INFO - debug_pipeline - ======================================================
[2025-04-25 08:18:01,690] - INFO - debug_pipeline - ========== Launching Model Trainer Pipeline ==========
[2025-04-25 08:18:01,694] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-25 08:18:01,701] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-25 08:18:01,705] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-25 08:18:01,707] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-25 08:18:01,708] - INFO - model_trainer_pipeline - ========== Model Training Stage Started ==========
[2025-04-25 08:18:01,708] - INFO - model_trainer - Initializing ModelTrainer with root_dir=artifacts\2025_04_25T07_17_51Z\model_trainer
[2025-04-25 08:18:02,978] - INFO - model_trainer - ========== Starting Model Training ==========
[2025-04-25 08:18:47,800] - ERROR - estimator - Failed to load model artifacts
Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\inference\estimator.py", line 19, in from_artifacts
    model = joblib.load(model_path)
  File "E:\MyProjects\networksecurity\venv\lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not GradientBoostingClassifier
[2025-04-25 08:18:47,802] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\inference\estimator.py], line [19], message: [expected str, bytes or os.PathLike object, not GradientBoostingClassifier]
[2025-04-25 08:18:47,802] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [146], message: [Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\inference\estimator.py], line [19], message: [expected str, bytes or os.PathLike object, not GradientBoostingClassifier]]
[2025-04-25 08:18:47,802] - ERROR - model_trainer_pipeline - Model Training Stage Failed
Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\inference\estimator.py", line 19, in from_artifacts
    model = joblib.load(model_path)
  File "E:\MyProjects\networksecurity\venv\lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not GradientBoostingClassifier

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py", line 146, in run_training
    network_model = NetworkModel.from_artifacts(
  File "E:\MyProjects\networksecurity\src\networksecurity\inference\estimator.py", line 26, in from_artifacts
    raise NetworkSecurityError(e, logger) from e
src.networksecurity.exception.exception.NetworkSecurityError: Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\inference\estimator.py], line [19], message: [expected str, bytes or os.PathLike object, not GradientBoostingClassifier]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\pipeline\model_trainer_pipeline.py", line 40, in run
    trainer_artifact = trainer.run_training()
  File "E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py", line 163, in run_training
    raise NetworkSecurityError(e, logger)
src.networksecurity.exception.exception.NetworkSecurityError: Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [146], message: [Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\inference\estimator.py], line [19], message: [expected str, bytes or os.PathLike object, not GradientBoostingClassifier]]
[2025-04-25 08:18:47,807] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\pipeline\model_trainer_pipeline.py], line [40], message: [Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [146], message: [Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\inference\estimator.py], line [19], message: [expected str, bytes or os.PathLike object, not GradientBoostingClassifier]]]
