[2025-04-12 18:23:14,181] - INFO - common - YAML loaded successfully from: 'config\config.yaml'
[2025-04-12 18:23:14,195] - INFO - common - YAML loaded successfully from: 'config\params.yaml'
[2025-04-12 18:23:14,195] - INFO - common - YAML loaded successfully from: 'config\schema.yaml'
[2025-04-12 18:23:14,195] - INFO - common - Created directory at: 'artifacts'
[2025-04-12 18:23:14,195] - INFO - common - Created directory at: 'artifacts/data_ingestion'
[2025-04-12 18:23:14,195] - INFO - data_ingestion - Connecting to MongoDB...
[2025-04-12 18:23:14,399] - ERROR - data_ingestion - Failed to load data from MongoDB.
[2025-04-12 18:23:14,399] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\data_ingestion.py], line [31], message: ['DataIngestionConfig' object has no attribute 'database_name']
