[2025-04-26 10:56:11,000] - INFO - debug_pipeline - ========== Launching Data Ingestion Pipeline ==========
[2025-04-26 10:56:11,016] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:56:11,022] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:56:11,024] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:56:11,027] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:56:11,027] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Started ==========
[2025-04-26 10:56:11,027] - INFO - data_ingestion - ========== Starting Data Ingestion ==========
[2025-04-26 10:56:11,191] - INFO - mongodb_handler - MongoClient initialized.
[2025-04-26 10:56:13,640] - INFO - mongodb_handler - Exported 22110 documents from network_security_db.phishing_records as DataFrame.
[2025-04-26 10:56:13,722] - INFO - mongodb_handler - MongoClient connection closed.
[2025-04-26 10:56:13,722] - INFO - data_ingestion - Fetched 22110 raw rows from data source.
[2025-04-26 10:56:13,727] - INFO - core - Created directory for Raw Data: 'artifacts/2025_04_26T09_56_08Z/data_ingestion/featurestore'
[2025-04-26 10:56:13,806] - INFO - core - Raw Data saved to: 'artifacts/2025_04_26T09_56_08Z/data_ingestion/featurestore/raw_data.csv'
[2025-04-26 10:56:13,806] - INFO - core - Directory already exists for Raw Data: 'data/raw'
[2025-04-26 10:56:13,895] - INFO - core - Raw Data saved to: 'data/raw/raw_data.csv'
[2025-04-26 10:56:13,899] - INFO - data_ingestion - Raw DataFrame cleaned successfully.
[2025-04-26 10:56:13,899] - INFO - core - Created directory for Cleaned (Ingested) Data: 'artifacts/2025_04_26T09_56_08Z/data_ingestion/ingested'
[2025-04-26 10:56:13,966] - INFO - core - Cleaned (Ingested) Data saved to: 'artifacts/2025_04_26T09_56_08Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-26 10:56:13,970] - INFO - data_ingestion - ========== Data Ingestion Completed ==========
[2025-04-26 10:56:13,970] - INFO - data_ingestion_pipeline - Data Ingestion Process Completed.

Data Ingestion Artifact:
  - Raw Artifact:         'artifacts/2025_04_26T09_56_08Z/data_ingestion/featurestore/raw_data.csv'
  - Raw DVC Path:         'data/raw/raw_data.csv'
  - Ingested Data Path:   'artifacts/2025_04_26T09_56_08Z/data_ingestion/ingested/ingested_data.csv'

[2025-04-26 10:56:13,970] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Completed ==========
[2025-04-26 10:56:13,970] - INFO - debug_pipeline - ========== Data Ingestion Pipeline Finished ==========
[2025-04-26 10:56:13,970] - INFO - debug_pipeline - ======================================================
[2025-04-26 10:56:13,970] - INFO - debug_pipeline - ========== Launching Data Validation Pipeline ==========
[2025-04-26 10:56:13,974] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:56:13,984] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:56:13,987] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:56:13,990] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:56:13,991] - INFO - data_validation_pipeline - ========= Data Validation Stage Started =========
[2025-04-26 10:56:14,024] - INFO - core - Ingested Data loaded from: 'artifacts/2025_04_26T09_56_08Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-26 10:56:14,050] - INFO - core - Validated Base Data loaded from: 'data/validated/validated_data.csv'
[2025-04-26 10:56:14,050] - INFO - data_validation - Running data validation...
[2025-04-26 10:56:14,052] - INFO - data_validation - Schema hash check passed.
[2025-04-26 10:56:14,054] - INFO - core - Created directory for Missing Value Report: 'artifacts/2025_04_26T09_56_08Z/data_validation/reports'
[2025-04-26 10:56:14,054] - INFO - core - Missing Value Report saved to: 'artifacts/2025_04_26T09_56_08Z/data_validation/reports/missing_values_report.json'
[2025-04-26 10:56:14,062] - INFO - core - Directory already exists for Duplicates Report: 'artifacts/2025_04_26T09_56_08Z/data_validation/reports'
[2025-04-26 10:56:14,062] - INFO - core - Duplicates Report saved to: 'artifacts/2025_04_26T09_56_08Z/data_validation/reports/duplicates_report.yaml'
[2025-04-26 10:56:14,078] - INFO - core - Directory already exists for Drift Result: 'artifacts/2025_04_26T09_56_08Z/data_validation/reports'
[2025-04-26 10:56:14,096] - INFO - core - Drift Result saved to: 'artifacts/2025_04_26T09_56_08Z/data_validation/reports/drift_report.yaml'
[2025-04-26 10:56:14,097] - INFO - core - Directory already exists for Validation Report: 'artifacts/2025_04_26T09_56_08Z/data_validation/reports'
[2025-04-26 10:56:14,098] - INFO - core - Validation Report saved to: 'artifacts/2025_04_26T09_56_08Z/data_validation/reports/validation_report.yaml'
[2025-04-26 10:56:14,099] - INFO - core - Created directory for Validated Data: 'artifacts/2025_04_26T09_56_08Z/data_validation/validated'
[2025-04-26 10:56:14,108] - INFO - core - Validated Data saved to: 'artifacts/2025_04_26T09_56_08Z/data_validation/validated/validated_data.csv'
[2025-04-26 10:56:14,108] - INFO - core - Directory already exists for Validated Data: 'data/validated'
[2025-04-26 10:56:14,132] - INFO - core - Validated Data saved to: 'data/validated/validated_data.csv'
[2025-04-26 10:56:14,132] - INFO - data_validation_pipeline - Data Validation Process Completed.

Data Validation Artifact:
  - Validated Data Path: 'artifacts/2025_04_26T09_56_08Z/data_validation/validated/validated_data.csv'
  - Validation Status:   'True'

[2025-04-26 10:56:14,132] - INFO - data_validation_pipeline - ========= Data Validation Stage Completed =========
[2025-04-26 10:56:14,132] - INFO - debug_pipeline - ========== Data Validation Pipeline Finished ==========
[2025-04-26 10:56:14,132] - INFO - debug_pipeline - ======================================================
[2025-04-26 10:56:14,132] - INFO - debug_pipeline - ========== Launching Data Transformation Pipeline ==========
[2025-04-26 10:56:14,132] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:56:14,153] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:56:14,153] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:56:14,159] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:56:14,159] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Started ==========
[2025-04-26 10:56:14,184] - INFO - core - Validated Data loaded from: 'artifacts/2025_04_26T09_56_08Z/data_validation/validated/validated_data.csv'
[2025-04-26 10:56:14,184] - INFO - data_transformation - ========== Starting Data Transformation ==========
[2025-04-26 10:56:14,202] - INFO - core - Created directory for X Preprocessor Pipeline: 'artifacts/2025_04_26T09_56_08Z/data_transformation/preprocessor'
[2025-04-26 10:56:14,205] - INFO - core - X Preprocessor Pipeline saved to: 'artifacts/2025_04_26T09_56_08Z/data_transformation/preprocessor/x_preprocessor.joblib'
[2025-04-26 10:56:14,205] - INFO - core - Directory already exists for Y Preprocessor Pipeline: 'artifacts/2025_04_26T09_56_08Z/data_transformation/preprocessor'
[2025-04-26 10:56:14,206] - INFO - core - Y Preprocessor Pipeline saved to: 'artifacts/2025_04_26T09_56_08Z/data_transformation/preprocessor/y_preprocessor.joblib'
[2025-04-26 10:56:14,206] - INFO - core - Created directory for X_train: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/train'
[2025-04-26 10:56:14,207] - INFO - core - X_train saved to: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/train/x_train.npy'
[2025-04-26 10:56:14,208] - INFO - core - Directory already exists for X_train: 'data/transformed/train'
[2025-04-26 10:56:14,208] - INFO - core - X_train saved to: 'data/transformed/train/x_train.npy'
[2025-04-26 10:56:14,209] - INFO - core - Directory already exists for y_train: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/train'
[2025-04-26 10:56:14,209] - INFO - core - y_train saved to: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/train/y_train.npy'
[2025-04-26 10:56:14,209] - INFO - core - Directory already exists for y_train: 'data/transformed/train'
[2025-04-26 10:56:14,210] - INFO - core - y_train saved to: 'data/transformed/train/y_train.npy'
[2025-04-26 10:56:14,210] - INFO - core - Created directory for X_val: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/val'
[2025-04-26 10:56:14,211] - INFO - core - X_val saved to: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/val/x_val.npy'
[2025-04-26 10:56:14,211] - INFO - core - Directory already exists for X_val: 'data/transformed/val'
[2025-04-26 10:56:14,211] - INFO - core - X_val saved to: 'data/transformed/val/x_val.npy'
[2025-04-26 10:56:14,211] - INFO - core - Directory already exists for y_val: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/val'
[2025-04-26 10:56:14,212] - INFO - core - y_val saved to: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/val/y_val.npy'
[2025-04-26 10:56:14,212] - INFO - core - Directory already exists for y_val: 'data/transformed/val'
[2025-04-26 10:56:14,212] - INFO - core - y_val saved to: 'data/transformed/val/y_val.npy'
[2025-04-26 10:56:14,212] - INFO - core - Created directory for X_test: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/test'
[2025-04-26 10:56:14,212] - INFO - core - X_test saved to: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/test/x_test.npy'
[2025-04-26 10:56:14,214] - INFO - core - Directory already exists for X_test: 'data/transformed/test'
[2025-04-26 10:56:14,214] - INFO - core - X_test saved to: 'data/transformed/test/x_test.npy'
[2025-04-26 10:56:14,214] - INFO - core - Directory already exists for y_test: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/test'
[2025-04-26 10:56:14,214] - INFO - core - y_test saved to: 'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/test/y_test.npy'
[2025-04-26 10:56:14,214] - INFO - core - Directory already exists for y_test: 'data/transformed/test'
[2025-04-26 10:56:14,214] - INFO - core - y_test saved to: 'data/transformed/test/y_test.npy'
[2025-04-26 10:56:14,214] - INFO - data_transformation - ========== Data Transformation Completed ==========
[2025-04-26 10:56:14,214] - INFO - data_transformation_pipeline - Data Transformation Completed Successfully: 
Data Transformation Artifact:
  - X-Train Data Path:    'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/train/x_train.npy'
  - Y-Train Data Path:    'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/train/y_train.npy'
  - X-Val Data Path:      'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/val/x_val.npy'
  - Y-Val Data Path:      'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/val/y_val.npy'
  - X-Test Data Path:     'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/test/x_test.npy'
  - Y-Test Data Path:     'artifacts/2025_04_26T09_56_08Z/data_transformation/transformed/test/y_test.npy'
  - X-Processor Path:     'artifacts/2025_04_26T09_56_08Z/data_transformation/preprocessor/x_preprocessor.joblib'
  - Y-Processor Path:     'artifacts/2025_04_26T09_56_08Z/data_transformation/preprocessor/y_preprocessor.joblib'

[2025-04-26 10:56:14,214] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Completed ==========
[2025-04-26 10:56:14,214] - INFO - debug_pipeline - ========== Data Transformation Pipeline Finished ==========
[2025-04-26 10:56:14,214] - INFO - debug_pipeline - ======================================================
[2025-04-26 10:56:14,214] - INFO - debug_pipeline - ========== Launching Model Trainer Pipeline ==========
[2025-04-26 10:56:14,220] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:56:14,226] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:56:14,228] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:56:14,234] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:56:14,234] - INFO - model_trainer_pipeline - ========== Model Training Stage Started ==========
[2025-04-26 10:56:14,235] - INFO - model_trainer - Initializing ModelTrainer with root_dir=artifacts\2025_04_26T09_56_08Z\model_trainer
[2025-04-26 10:56:15,392] - INFO - model_trainer - ========== Starting Model Training ==========
[2025-04-26 10:56:54,800] - INFO - core - Created directory for Base Model: 'artifacts/2025_04_26T09_56_08Z/model_trainer/base_model'
[2025-04-26 10:56:54,816] - INFO - core - Base Model saved to: 'artifacts/2025_04_26T09_56_08Z/model_trainer/base_model/base_model.joblib'
[2025-04-26 10:56:55,219] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [145], message: [NetworkModel.from_artifacts() got an unexpected keyword argument 'model']
[2025-04-26 10:56:55,219] - ERROR - model_trainer_pipeline - Model Training Stage Failed
Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py", line 145, in run_training
    network_model = NetworkModel.from_artifacts(
TypeError: NetworkModel.from_artifacts() got an unexpected keyword argument 'model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\pipeline\model_trainer_pipeline.py", line 40, in run
    trainer_artifact = trainer.run_training()
  File "E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py", line 166, in run_training
    raise NetworkSecurityError(e, logger) from e
src.networksecurity.exception.exception.NetworkSecurityError: Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [145], message: [NetworkModel.from_artifacts() got an unexpected keyword argument 'model']
[2025-04-26 10:56:55,219] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\pipeline\model_trainer_pipeline.py], line [40], message: [Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [145], message: [NetworkModel.from_artifacts() got an unexpected keyword argument 'model']]
