[2025-04-26 10:40:04,686] - INFO - debug_pipeline - ========== Launching Data Ingestion Pipeline ==========
[2025-04-26 10:40:04,693] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:40:04,700] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:40:04,703] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:40:04,707] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:40:04,707] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Started ==========
[2025-04-26 10:40:04,707] - INFO - data_ingestion - ========== Starting Data Ingestion ==========
[2025-04-26 10:40:04,929] - INFO - mongodb_handler - MongoClient initialized.
[2025-04-26 10:40:07,662] - INFO - mongodb_handler - Exported 22110 documents from network_security_db.phishing_records as DataFrame.
[2025-04-26 10:40:07,723] - INFO - mongodb_handler - MongoClient connection closed.
[2025-04-26 10:40:07,723] - INFO - data_ingestion - Fetched 22110 raw rows from data source.
[2025-04-26 10:40:07,723] - INFO - core - Created directory for Raw Data: 'artifacts/2025_04_26T09_39_59Z/data_ingestion/featurestore'
[2025-04-26 10:40:07,807] - INFO - core - Raw Data saved to: 'artifacts/2025_04_26T09_39_59Z/data_ingestion/featurestore/raw_data.csv'
[2025-04-26 10:40:07,807] - INFO - core - Directory already exists for Raw Data: 'data/raw'
[2025-04-26 10:40:07,891] - INFO - core - Raw Data saved to: 'data/raw/raw_data.csv'
[2025-04-26 10:40:07,900] - INFO - data_ingestion - Raw DataFrame cleaned successfully.
[2025-04-26 10:40:07,900] - INFO - core - Created directory for Cleaned (Ingested) Data: 'artifacts/2025_04_26T09_39_59Z/data_ingestion/ingested'
[2025-04-26 10:40:07,966] - INFO - core - Cleaned (Ingested) Data saved to: 'artifacts/2025_04_26T09_39_59Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-26 10:40:07,966] - INFO - data_ingestion - ========== Data Ingestion Completed ==========
[2025-04-26 10:40:07,970] - INFO - data_ingestion_pipeline - Data Ingestion Process Completed.

Data Ingestion Artifact:
  - Raw Artifact:         'artifacts/2025_04_26T09_39_59Z/data_ingestion/featurestore/raw_data.csv'
  - Raw DVC Path:         'data/raw/raw_data.csv'
  - Ingested Data Path:   'artifacts/2025_04_26T09_39_59Z/data_ingestion/ingested/ingested_data.csv'

[2025-04-26 10:40:07,970] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Completed ==========
[2025-04-26 10:40:07,970] - INFO - debug_pipeline - ========== Data Ingestion Pipeline Finished ==========
[2025-04-26 10:40:07,970] - INFO - debug_pipeline - ======================================================
[2025-04-26 10:40:07,974] - INFO - debug_pipeline - ========== Launching Data Validation Pipeline ==========
[2025-04-26 10:40:07,977] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:40:07,984] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:40:07,988] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:40:07,991] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:40:07,991] - INFO - data_validation_pipeline - ========= Data Validation Stage Started =========
[2025-04-26 10:40:08,024] - INFO - core - Ingested Data loaded from: 'artifacts/2025_04_26T09_39_59Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-26 10:40:08,046] - INFO - core - Validated Base Data loaded from: 'data/validated/validated_data.csv'
[2025-04-26 10:40:08,049] - INFO - data_validation - Running data validation...
[2025-04-26 10:40:08,050] - INFO - data_validation - Schema hash check passed.
[2025-04-26 10:40:08,050] - INFO - core - Created directory for Missing Value Report: 'artifacts/2025_04_26T09_39_59Z/data_validation/reports'
[2025-04-26 10:40:08,054] - INFO - core - Missing Value Report saved to: 'artifacts/2025_04_26T09_39_59Z/data_validation/reports/missing_values_report.json'
[2025-04-26 10:40:08,062] - INFO - core - Directory already exists for Duplicates Report: 'artifacts/2025_04_26T09_39_59Z/data_validation/reports'
[2025-04-26 10:40:08,062] - INFO - core - Duplicates Report saved to: 'artifacts/2025_04_26T09_39_59Z/data_validation/reports/duplicates_report.yaml'
[2025-04-26 10:40:08,087] - INFO - core - Directory already exists for Drift Result: 'artifacts/2025_04_26T09_39_59Z/data_validation/reports'
[2025-04-26 10:40:08,095] - INFO - core - Drift Result saved to: 'artifacts/2025_04_26T09_39_59Z/data_validation/reports/drift_report.yaml'
[2025-04-26 10:40:08,095] - INFO - core - Directory already exists for Validation Report: 'artifacts/2025_04_26T09_39_59Z/data_validation/reports'
[2025-04-26 10:40:08,097] - INFO - core - Validation Report saved to: 'artifacts/2025_04_26T09_39_59Z/data_validation/reports/validation_report.yaml'
[2025-04-26 10:40:08,097] - INFO - core - Created directory for Validated Data: 'artifacts/2025_04_26T09_39_59Z/data_validation/validated'
[2025-04-26 10:40:08,116] - INFO - core - Validated Data saved to: 'artifacts/2025_04_26T09_39_59Z/data_validation/validated/validated_data.csv'
[2025-04-26 10:40:08,116] - INFO - core - Directory already exists for Validated Data: 'data/validated'
[2025-04-26 10:40:08,137] - INFO - core - Validated Data saved to: 'data/validated/validated_data.csv'
[2025-04-26 10:40:08,137] - INFO - data_validation_pipeline - Data Validation Process Completed.

Data Validation Artifact:
  - Validated Data Path: 'artifacts/2025_04_26T09_39_59Z/data_validation/validated/validated_data.csv'
  - Validation Status:   'True'

[2025-04-26 10:40:08,137] - INFO - data_validation_pipeline - ========= Data Validation Stage Completed =========
[2025-04-26 10:40:08,137] - INFO - debug_pipeline - ========== Data Validation Pipeline Finished ==========
[2025-04-26 10:40:08,137] - INFO - debug_pipeline - ======================================================
[2025-04-26 10:40:08,137] - INFO - debug_pipeline - ========== Launching Data Transformation Pipeline ==========
[2025-04-26 10:40:08,143] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:40:08,150] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:40:08,153] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:40:08,155] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:40:08,156] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Started ==========
[2025-04-26 10:40:08,183] - INFO - core - Validated Data loaded from: 'artifacts/2025_04_26T09_39_59Z/data_validation/validated/validated_data.csv'
[2025-04-26 10:40:08,183] - INFO - data_transformation - ========== Starting Data Transformation ==========
[2025-04-26 10:40:08,214] - INFO - core - Created directory for X Preprocessor Pipeline: 'artifacts/2025_04_26T09_39_59Z/data_transformation/preprocessor'
[2025-04-26 10:40:08,216] - INFO - core - X Preprocessor Pipeline saved to: 'artifacts/2025_04_26T09_39_59Z/data_transformation/preprocessor/x_preprocessor.joblib'
[2025-04-26 10:40:08,216] - INFO - core - Directory already exists for Y Preprocessor Pipeline: 'artifacts/2025_04_26T09_39_59Z/data_transformation/preprocessor'
[2025-04-26 10:40:08,217] - INFO - core - Y Preprocessor Pipeline saved to: 'artifacts/2025_04_26T09_39_59Z/data_transformation/preprocessor/y_preprocessor.joblib'
[2025-04-26 10:40:08,217] - INFO - core - Created directory for X_train: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/train'
[2025-04-26 10:40:08,217] - INFO - core - X_train saved to: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/train/x_train.npy'
[2025-04-26 10:40:08,217] - INFO - core - Directory already exists for X_train: 'data/transformed/train'
[2025-04-26 10:40:08,217] - INFO - core - X_train saved to: 'data/transformed/train/x_train.npy'
[2025-04-26 10:40:08,217] - INFO - core - Directory already exists for y_train: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/train'
[2025-04-26 10:40:08,219] - INFO - core - y_train saved to: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/train/y_train.npy'
[2025-04-26 10:40:08,219] - INFO - core - Directory already exists for y_train: 'data/transformed/train'
[2025-04-26 10:40:08,220] - INFO - core - y_train saved to: 'data/transformed/train/y_train.npy'
[2025-04-26 10:40:08,220] - INFO - core - Created directory for X_val: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/val'
[2025-04-26 10:40:08,221] - INFO - core - X_val saved to: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/val/x_val.npy'
[2025-04-26 10:40:08,221] - INFO - core - Directory already exists for X_val: 'data/transformed/val'
[2025-04-26 10:40:08,221] - INFO - core - X_val saved to: 'data/transformed/val/x_val.npy'
[2025-04-26 10:40:08,222] - INFO - core - Directory already exists for y_val: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/val'
[2025-04-26 10:40:08,222] - INFO - core - y_val saved to: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/val/y_val.npy'
[2025-04-26 10:40:08,222] - INFO - core - Directory already exists for y_val: 'data/transformed/val'
[2025-04-26 10:40:08,223] - INFO - core - y_val saved to: 'data/transformed/val/y_val.npy'
[2025-04-26 10:40:08,224] - INFO - core - Created directory for X_test: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/test'
[2025-04-26 10:40:08,224] - INFO - core - X_test saved to: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/test/x_test.npy'
[2025-04-26 10:40:08,224] - INFO - core - Directory already exists for X_test: 'data/transformed/test'
[2025-04-26 10:40:08,224] - INFO - core - X_test saved to: 'data/transformed/test/x_test.npy'
[2025-04-26 10:40:08,224] - INFO - core - Directory already exists for y_test: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/test'
[2025-04-26 10:40:08,224] - INFO - core - y_test saved to: 'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/test/y_test.npy'
[2025-04-26 10:40:08,224] - INFO - core - Directory already exists for y_test: 'data/transformed/test'
[2025-04-26 10:40:08,224] - INFO - core - y_test saved to: 'data/transformed/test/y_test.npy'
[2025-04-26 10:40:08,224] - INFO - data_transformation - ========== Data Transformation Completed ==========
[2025-04-26 10:40:08,224] - INFO - data_transformation_pipeline - Data Transformation Completed Successfully: 
Data Transformation Artifact:
  - X-Train Data Path:    'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/train/x_train.npy'
  - Y-Train Data Path:    'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/train/y_train.npy'
  - X-Val Data Path:      'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/val/x_val.npy'
  - Y-Val Data Path:      'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/val/y_val.npy'
  - X-Test Data Path:     'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/test/x_test.npy'
  - Y-Test Data Path:     'artifacts/2025_04_26T09_39_59Z/data_transformation/transformed/test/y_test.npy'

[2025-04-26 10:40:08,224] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Completed ==========
[2025-04-26 10:40:08,224] - INFO - debug_pipeline - ========== Data Transformation Pipeline Finished ==========
[2025-04-26 10:40:08,228] - INFO - debug_pipeline - ======================================================
[2025-04-26 10:40:08,229] - INFO - debug_pipeline - ========== Launching Model Trainer Pipeline ==========
[2025-04-26 10:40:08,232] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:40:08,239] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:40:08,241] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:40:08,245] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:40:08,245] - INFO - model_trainer_pipeline - ========== Model Training Stage Started ==========
[2025-04-26 10:40:08,245] - INFO - model_trainer - Initializing ModelTrainer with root_dir=artifacts\2025_04_26T09_39_59Z\model_trainer
[2025-04-26 10:40:09,495] - INFO - model_trainer - ========== Starting Model Training ==========
[2025-04-26 10:40:42,698] - INFO - core - Created directory for Base Model: 'artifacts/2025_04_26T09_39_59Z/model_trainer/base_model'
[2025-04-26 10:40:42,714] - INFO - core - Base Model saved to: 'artifacts/2025_04_26T09_39_59Z/model_trainer/base_model/base_model.joblib'
[2025-04-26 10:40:43,115] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [147], message: ['DataTransformationArtifact' object has no attribute 'x_preprocessor_filepath']
[2025-04-26 10:40:43,115] - ERROR - model_trainer_pipeline - Model Training Stage Failed
Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py", line 147, in run_training
    x_preprocessor_path=self.transformation_artifact.x_preprocessor_filepath,
AttributeError: 'DataTransformationArtifact' object has no attribute 'x_preprocessor_filepath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\pipeline\model_trainer_pipeline.py", line 40, in run
    trainer_artifact = trainer.run_training()
  File "E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py", line 166, in run_training
    raise NetworkSecurityError(e, logger) from e
src.networksecurity.exception.exception.NetworkSecurityError: Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [147], message: ['DataTransformationArtifact' object has no attribute 'x_preprocessor_filepath']
[2025-04-26 10:40:43,115] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\pipeline\model_trainer_pipeline.py], line [40], message: [Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [147], message: ['DataTransformationArtifact' object has no attribute 'x_preprocessor_filepath']]
