[2025-04-12 16:13:23,594] - INFO - common - YAML loaded successfully from: 'config\config.yaml'
[2025-04-12 16:13:23,594] - INFO - common - YAML loaded successfully from: 'config\params.yaml'
[2025-04-12 16:13:23,594] - INFO - common - YAML loaded successfully from: 'config\schema.yaml'
[2025-04-12 16:13:23,594] - INFO - common - Created directory at: 'artifacts'
[2025-04-12 16:13:23,594] - INFO - common - Created directory at: 'artifacts/mongodb'
[2025-04-12 16:13:24,024] - INFO - common - CSV converted and saved to: 'artifacts/mongodb/input_data_json.json'
[2025-04-12 16:13:24,924] - INFO - mongo_handler - Attempting to connect to MongoDB...
[2025-04-12 16:13:25,003] - INFO - mongo_handler - MongoDB connection established.
[2025-04-12 16:13:25,003] - INFO - mongo_handler - Using database: 'network_security_db'
[2025-04-12 16:13:25,003] - INFO - mongo_handler - Using collection: 'phishing_records'
[2025-04-12 16:13:25,003] - INFO - mongo_handler - Inserting 11055 record(s) into MongoDB...
[2025-04-12 16:13:37,498] - INFO - mongo_handler - 11055 record(s) inserted successfully into MongoDB.
[2025-04-12 16:13:40,449] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\dbhandler\mongo_handler.py], line [80], message: [ac-zk2ogc7-shard-00-01.iuvpjek.mongodb.net:27017: timed out (configured timeouts: connectTimeoutMS: 20000.0ms)]
