[2025-04-26 10:48:53,537] - INFO - debug_pipeline - ========== Launching Data Ingestion Pipeline ==========
[2025-04-26 10:48:53,537] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:48:53,537] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:48:53,558] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:48:53,560] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:48:53,560] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Started ==========
[2025-04-26 10:48:53,560] - INFO - data_ingestion - ========== Starting Data Ingestion ==========
[2025-04-26 10:48:53,691] - INFO - mongodb_handler - MongoClient initialized.
[2025-04-26 10:48:56,917] - INFO - mongodb_handler - Exported 22110 documents from network_security_db.phishing_records as DataFrame.
[2025-04-26 10:48:56,986] - INFO - mongodb_handler - MongoClient connection closed.
[2025-04-26 10:48:56,986] - INFO - data_ingestion - Fetched 22110 raw rows from data source.
[2025-04-26 10:48:56,986] - INFO - core - Created directory for Raw Data: 'artifacts/2025_04_26T09_48_51Z/data_ingestion/featurestore'
[2025-04-26 10:48:57,072] - INFO - core - Raw Data saved to: 'artifacts/2025_04_26T09_48_51Z/data_ingestion/featurestore/raw_data.csv'
[2025-04-26 10:48:57,072] - INFO - core - Directory already exists for Raw Data: 'data/raw'
[2025-04-26 10:48:57,158] - INFO - core - Raw Data saved to: 'data/raw/raw_data.csv'
[2025-04-26 10:48:57,162] - INFO - data_ingestion - Raw DataFrame cleaned successfully.
[2025-04-26 10:48:57,162] - INFO - core - Created directory for Cleaned (Ingested) Data: 'artifacts/2025_04_26T09_48_51Z/data_ingestion/ingested'
[2025-04-26 10:48:57,228] - INFO - core - Cleaned (Ingested) Data saved to: 'artifacts/2025_04_26T09_48_51Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-26 10:48:57,232] - INFO - data_ingestion - ========== Data Ingestion Completed ==========
[2025-04-26 10:48:57,232] - INFO - data_ingestion_pipeline - Data Ingestion Process Completed.

Data Ingestion Artifact:
  - Raw Artifact:         'artifacts/2025_04_26T09_48_51Z/data_ingestion/featurestore/raw_data.csv'
  - Raw DVC Path:         'data/raw/raw_data.csv'
  - Ingested Data Path:   'artifacts/2025_04_26T09_48_51Z/data_ingestion/ingested/ingested_data.csv'

[2025-04-26 10:48:57,232] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Completed ==========
[2025-04-26 10:48:57,232] - INFO - debug_pipeline - ========== Data Ingestion Pipeline Finished ==========
[2025-04-26 10:48:57,232] - INFO - debug_pipeline - ======================================================
[2025-04-26 10:48:57,237] - INFO - debug_pipeline - ========== Launching Data Validation Pipeline ==========
[2025-04-26 10:48:57,240] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:48:57,245] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:48:57,249] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:48:57,254] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:48:57,254] - INFO - data_validation_pipeline - ========= Data Validation Stage Started =========
[2025-04-26 10:48:57,287] - INFO - core - Ingested Data loaded from: 'artifacts/2025_04_26T09_48_51Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-26 10:48:57,312] - INFO - core - Validated Base Data loaded from: 'data/validated/validated_data.csv'
[2025-04-26 10:48:57,312] - INFO - data_validation - Running data validation...
[2025-04-26 10:48:57,312] - INFO - data_validation - Schema hash check passed.
[2025-04-26 10:48:57,312] - INFO - core - Created directory for Missing Value Report: 'artifacts/2025_04_26T09_48_51Z/data_validation/reports'
[2025-04-26 10:48:57,316] - INFO - core - Missing Value Report saved to: 'artifacts/2025_04_26T09_48_51Z/data_validation/reports/missing_values_report.json'
[2025-04-26 10:48:57,325] - INFO - core - Directory already exists for Duplicates Report: 'artifacts/2025_04_26T09_48_51Z/data_validation/reports'
[2025-04-26 10:48:57,326] - INFO - core - Duplicates Report saved to: 'artifacts/2025_04_26T09_48_51Z/data_validation/reports/duplicates_report.yaml'
[2025-04-26 10:48:57,349] - INFO - core - Directory already exists for Drift Result: 'artifacts/2025_04_26T09_48_51Z/data_validation/reports'
[2025-04-26 10:48:57,356] - INFO - core - Drift Result saved to: 'artifacts/2025_04_26T09_48_51Z/data_validation/reports/drift_report.yaml'
[2025-04-26 10:48:57,356] - INFO - core - Directory already exists for Validation Report: 'artifacts/2025_04_26T09_48_51Z/data_validation/reports'
[2025-04-26 10:48:57,359] - INFO - core - Validation Report saved to: 'artifacts/2025_04_26T09_48_51Z/data_validation/reports/validation_report.yaml'
[2025-04-26 10:48:57,359] - INFO - core - Created directory for Validated Data: 'artifacts/2025_04_26T09_48_51Z/data_validation/validated'
[2025-04-26 10:48:57,379] - INFO - core - Validated Data saved to: 'artifacts/2025_04_26T09_48_51Z/data_validation/validated/validated_data.csv'
[2025-04-26 10:48:57,379] - INFO - core - Directory already exists for Validated Data: 'data/validated'
[2025-04-26 10:48:57,402] - INFO - core - Validated Data saved to: 'data/validated/validated_data.csv'
[2025-04-26 10:48:57,402] - INFO - data_validation_pipeline - Data Validation Process Completed.

Data Validation Artifact:
  - Validated Data Path: 'artifacts/2025_04_26T09_48_51Z/data_validation/validated/validated_data.csv'
  - Validation Status:   'True'

[2025-04-26 10:48:57,402] - INFO - data_validation_pipeline - ========= Data Validation Stage Completed =========
[2025-04-26 10:48:57,403] - INFO - debug_pipeline - ========== Data Validation Pipeline Finished ==========
[2025-04-26 10:48:57,403] - INFO - debug_pipeline - ======================================================
[2025-04-26 10:48:57,403] - INFO - debug_pipeline - ========== Launching Data Transformation Pipeline ==========
[2025-04-26 10:48:57,404] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-26 10:48:57,413] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-26 10:48:57,416] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-26 10:48:57,416] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-26 10:48:57,420] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Started ==========
[2025-04-26 10:48:57,445] - INFO - core - Validated Data loaded from: 'artifacts/2025_04_26T09_48_51Z/data_validation/validated/validated_data.csv'
[2025-04-26 10:48:57,445] - INFO - data_transformation - ========== Starting Data Transformation ==========
[2025-04-26 10:48:57,462] - INFO - core - Created directory for X Preprocessor Pipeline: 'artifacts/2025_04_26T09_48_51Z/data_transformation/preprocessor'
[2025-04-26 10:48:57,466] - INFO - core - X Preprocessor Pipeline saved to: 'artifacts/2025_04_26T09_48_51Z/data_transformation/preprocessor/x_preprocessor.joblib'
[2025-04-26 10:48:57,467] - INFO - core - Directory already exists for Y Preprocessor Pipeline: 'artifacts/2025_04_26T09_48_51Z/data_transformation/preprocessor'
[2025-04-26 10:48:57,468] - INFO - core - Y Preprocessor Pipeline saved to: 'artifacts/2025_04_26T09_48_51Z/data_transformation/preprocessor/y_preprocessor.joblib'
[2025-04-26 10:48:57,469] - INFO - core - Created directory for X_train: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/train'
[2025-04-26 10:48:57,470] - INFO - core - X_train saved to: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/train/x_train.npy'
[2025-04-26 10:48:57,470] - INFO - core - Directory already exists for X_train: 'data/transformed/train'
[2025-04-26 10:48:57,470] - INFO - core - X_train saved to: 'data/transformed/train/x_train.npy'
[2025-04-26 10:48:57,471] - INFO - core - Directory already exists for y_train: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/train'
[2025-04-26 10:48:57,471] - INFO - core - y_train saved to: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/train/y_train.npy'
[2025-04-26 10:48:57,471] - INFO - core - Directory already exists for y_train: 'data/transformed/train'
[2025-04-26 10:48:57,472] - INFO - core - y_train saved to: 'data/transformed/train/y_train.npy'
[2025-04-26 10:48:57,472] - INFO - core - Created directory for X_val: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/val'
[2025-04-26 10:48:57,473] - INFO - core - X_val saved to: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/val/x_val.npy'
[2025-04-26 10:48:57,473] - INFO - core - Directory already exists for X_val: 'data/transformed/val'
[2025-04-26 10:48:57,473] - INFO - core - X_val saved to: 'data/transformed/val/x_val.npy'
[2025-04-26 10:48:57,474] - INFO - core - Directory already exists for y_val: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/val'
[2025-04-26 10:48:57,474] - INFO - core - y_val saved to: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/val/y_val.npy'
[2025-04-26 10:48:57,474] - INFO - core - Directory already exists for y_val: 'data/transformed/val'
[2025-04-26 10:48:57,474] - INFO - core - y_val saved to: 'data/transformed/val/y_val.npy'
[2025-04-26 10:48:57,474] - INFO - core - Created directory for X_test: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/test'
[2025-04-26 10:48:57,474] - INFO - core - X_test saved to: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/test/x_test.npy'
[2025-04-26 10:48:57,474] - INFO - core - Directory already exists for X_test: 'data/transformed/test'
[2025-04-26 10:48:57,474] - INFO - core - X_test saved to: 'data/transformed/test/x_test.npy'
[2025-04-26 10:48:57,474] - INFO - core - Directory already exists for y_test: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/test'
[2025-04-26 10:48:57,474] - INFO - core - y_test saved to: 'artifacts/2025_04_26T09_48_51Z/data_transformation/transformed/test/y_test.npy'
[2025-04-26 10:48:57,474] - INFO - core - Directory already exists for y_test: 'data/transformed/test'
[2025-04-26 10:48:57,478] - INFO - core - y_test saved to: 'data/transformed/test/y_test.npy'
[2025-04-26 10:48:57,478] - INFO - data_transformation - ========== Data Transformation Completed ==========
[2025-04-26 10:48:57,478] - ERROR - data_transformation - Data transformation failed.
[2025-04-26 10:48:57,478] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\data_transformation.py], line [110], message: [DataTransformationArtifact.__init__() missing 2 required positional arguments: 'x_preprocessor_filepath' and 'y_preprocessor_filepath']
[2025-04-26 10:48:57,479] - ERROR - data_transformation_pipeline - Data Transformation Stage Failed
Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\components\data_transformation.py", line 110, in run_transformation
    return DataTransformationArtifact(
TypeError: DataTransformationArtifact.__init__() missing 2 required positional arguments: 'x_preprocessor_filepath' and 'y_preprocessor_filepath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\pipeline\data_transformation_pipeline.py", line 38, in run
    transformation_artifact = transformer.run_transformation()
  File "E:\MyProjects\networksecurity\src\networksecurity\components\data_transformation.py", line 121, in run_transformation
    raise NetworkSecurityError(e, logger) from e
src.networksecurity.exception.exception.NetworkSecurityError: Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\data_transformation.py], line [110], message: [DataTransformationArtifact.__init__() missing 2 required positional arguments: 'x_preprocessor_filepath' and 'y_preprocessor_filepath']
[2025-04-26 10:48:57,479] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\pipeline\data_transformation_pipeline.py], line [38], message: [Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\data_transformation.py], line [110], message: [DataTransformationArtifact.__init__() missing 2 required positional arguments: 'x_preprocessor_filepath' and 'y_preprocessor_filepath']]
