[2025-04-14 10:35:18,519] - INFO - common - YAML loaded successfully from: 'config/config.yaml'
[2025-04-14 10:35:18,519] - INFO - common - YAML loaded successfully from: 'config/params.yaml'
[2025-04-14 10:35:18,519] - INFO - common - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-14 10:35:18,519] - INFO - common - Created directory at: 'artifacts/20250414_103518'
[2025-04-14 10:35:18,519] - INFO - common - Created directory at: 'artifacts/20250414_103518/mongo_handler'
[2025-04-14 10:35:19,576] - INFO - common - Created directory for JSON output at: 'artifacts/20250414_103518/mongo_handler/JSON_data'
[2025-04-14 10:35:20,026] - INFO - common - CSV converted and saved to: 'artifacts/20250414_103518/mongo_handler/JSON_data/input_data_json.json'
[2025-04-14 10:35:20,041] - INFO - mongo_handler - Attempting to connect to MongoDB...
[2025-04-14 10:35:20,148] - INFO - mongo_handler - MongoDB connection established.
[2025-04-14 10:35:20,160] - INFO - mongo_handler - Using database: 'network_security_db'
[2025-04-14 10:35:20,162] - INFO - mongo_handler - Using collection: 'phishing_records'
[2025-04-14 10:35:20,162] - INFO - mongo_handler - Inserting 11055 record(s) into MongoDB...
[2025-04-14 10:35:32,543] - INFO - mongo_handler - 11055 record(s) inserted successfully into MongoDB.
[2025-04-14 10:35:32,570] - INFO - common - Created directory at: 'artifacts/20250414_103518/data_ingestion/featurestore'
[2025-04-14 10:35:32,571] - INFO - common - Created directory at: 'artifacts/20250414_103518/data_ingestion/ingested'
[2025-04-14 10:35:32,571] - INFO - data_ingestion - Connecting to MongoDB...
[2025-04-14 10:35:32,659] - INFO - data_ingestion - Reading data from MongoDB: 'network_security_db/phishing_records'
[2025-04-14 10:35:39,327] - ERROR - data_ingestion - Failed to load data from MongoDB.
[2025-04-14 10:35:39,327] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\data_ingestion.py], line [48], message: [ac-zk2ogc7-shard-00-01.iuvpjek.mongodb.net:27017: timed out (configured timeouts: connectTimeoutMS: 20000.0ms)]
